---
- hosts: all
  user: ubuntu
  become: yes
  tasks:
    - name: Install Apache 
      apt: 
        name: apache2
        state: latest
    
    #Starting apache service
    - name: Start and enable apache service
      service:
        name: apache2
        state: started
        enabled: yes
      
    - name: Configure firewall to allow HTTP traffic (HTTP is port 80)
      ufw: 
        rule: allow
        port: 80
        proto: tcp
        state: enabled
    
      #Add task to test default configuration of apache
    - name: Test Apache
      uri:
        url: http://{{ ansible_host }}
        status_code: 200
      register: response
      ignore_errors: yes
    
    - name: Display test result
      debug:
        var: response.status
